### PR TITLE
fix: Add missing webhook events

### PR DESCRIPTION
**Pull request by PatrykPlewaOfficial**
Connected with #120

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@PatrykPlewaOfficial please refer to the [documentation](https://developer.crowdin.com/api/v2/#operation/api.projects.webhooks.post) to see all the events. Also, I'd suggest placing events in the same order as it is in the docs

**Comment by PatrykPlewaOfficial** [comment]
> @PatrykPlewaOfficial please refer to the [documentation](https://developer.crowdin.com/api/v2/#operation/api.projects.webhooks.post) to see all the events. Also, I'd suggest placing events in the same order as it is in the docs

All included and ordered.

**Comment by andrii-bodnar** [comment]
@PatrykPlewaOfficial awesome, LGTM, thanks a lot! 🚀

**Review by andrii-bodnar — APPROVED** [review]

**Comment by andrii-bodnar** [comment]
@PatrykPlewaOfficial just released a new version - [2.13.0](https://github.com/crowdin/crowdin-api-client-dotnet/releases/tag/2.13.0)

**Pull request merged**
