### PR TITLE
feat(screenshots): add the stringIds parameter support

### LINKED ISSUE #256: Screenshots APIs: add the `stringIds` parameter support
The List Screenshots API has a new parameter called `stringIds` which allows you to filter screenshots by multiple string identifiers.

The existing `stringId` parameter is deprecated and will be removed in the future.

Things to do:

- Add support for the `stringIds` parameter in this API client.
- Mark the `stringId' parameter as deprecated.
- Check if other parameters need to be updated.

**References:**
- [List Screenshots](https://support.crowdin.com/developer/api/v2/#tag/Screenshots/operation/api.projects.screenshots.getMany)

### PR DESCRIPTION
**Pull request by EvilKot**
Closes #256

### CODE REVIEW

**Comment by EvilKot** [comment]
Hello, creating a PR in relation to https://github.com/crowdin/crowdin-api-client-dotnet/issues/256#issuecomment-2411097527

I haven't found any tests related to InternalExtensions, except [one checking orderBy string generation](https://github.com/crowdin/crowdin-api-client-dotnet/blob/a52b611ef5d1eccec424c5620567d490da76aac4/tests/Crowdin.Api.Tests/Common/SortingTests.cs#L39).
Also there's no tests checking Screenshots.ListScreenshots method ([only this ones](https://github.com/crowdin/crowdin-api-client-dotnet/blob/a52b611ef5d1eccec424c5620567d490da76aac4/tests/Crowdin.Api.Tests/Screenshots/ScreenshotsApiTests.cs)) so i have no reference/example how to add a new ones.

If it's a mandatory, I'd be really grateful for any help and tips how i could add them.

**Comment by andrii-bodnar** [comment]
Hello @EvilKot, thanks a lot for the contribution!

It would be nice to add tests for the `InternalExtensions` class and `Screenshots.ListScreenshots` method. For reference, I think you can use the `ProjectsApiTests:ListProjects` test case. 

The testing approach requires some boilerplate code like resources (e.g. [Projects.resx](https://github.com/crowdin/crowdin-api-client-dotnet/blob/a52b611ef5d1eccec424c5620567d490da76aac4/tests/Crowdin.Api.Tests/Core/Resources/Projects.resx), [Projects.Designer.cs](https://github.com/crowdin/crowdin-api-client-dotnet/blob/a52b611ef5d1eccec424c5620567d490da76aac4/tests/Crowdin.Api.Tests/Core/Resources/Projects.Designer.cs)). I'm not quite sure how this code is generated.

**Comment by EvilKot** [comment]
Thank you, @andrii-bodnar!

For `Screenshots.ListScreenshots` i've added a test based on example you provided. I however manually adjusted corresponsing .resx and .Designer.cs files. 

For `InternalExtensions` i'm not sure i'm going in a right way and if it's actually worth to cover it with tests:
- Most of the class methods are already being tested indirectly.
- I placed my InternalExtensionsTest.cs file in tests/Crowdin.Api.Tests/Core directory, mirroring the placement of  InternalExtensions.cs located in  src/Crowdin.Api/Core, similar to how it's done for other tests, however Core directory inside Crowdin.Api.Tests projects serves a bit different purpose and now only contains shared test utilities and .resx files. If the long term goal is to cover src/Crowdin.Api/Core with tests, then i'd suggest moving util and .resx files to another directory, idk, like tests/Crowdin.Api.Tests/TestUtils?
- Covered query string generation methods.

One more thing - i'm struggling a bit with indentation settings used in this repo. 
Originally my IDE attempted to remove any whitespaces from blank lines.

🥹

**Comment by andrii-bodnar** [comment]
@EvilKot sure, it's definitely out of the scope of the current PR

**Comment by andrii-bodnar** [comment]
@EvilKot I just created a separate issue for that - https://github.com/crowdin/crowdin-api-client-dotnet/issues/272

**Review by andrii-bodnar — APPROVED** [review]
Looks good to me, thanks @EvilKot!

**Comment by EvilKot** [comment]
Yay, thank you for walking me through!

**Pull request merged**
