### PR TITLE
fix: BuildStatus description casing inconsistency.

### PR DESCRIPTION
**Pull request by PatrickMNL**
Purposed fix for #167.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Honestly, I'm already not sure if this is a good idea :(

It adds extra complication for end users. Maybe it would be better to handle this inconsistency with the "temporary" fix? But it will no longer be temporary

We'll just hide this API design mistake from the end users.

**Comment by PatrickMNL** [comment]
@andrii-bodnar I definitely agree on that part, I don't mind accepting the 'workaround' as permanent fix. We can make it a little prettier by swapping around the descriptions. (Making 'in_progress' the default and 'inProgress' the one fixed by the workaround).

**Comment by PatrickMNL** [comment]
@andrii-bodnar Updated the PR accordingly.

**Comment by andrii-bodnar** [comment]
@PatrickMNL great, looks good to me, thanks a lot!

**Review by andrii-bodnar — APPROVED** [review]

**Pull request merged**
