### PR TITLE
fix webhook response serialization error

### PR DESCRIPTION
**Pull request by duyguyildirantekin**
fix for webhook response serialization error

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
Hi @duyguyildirantekin, thanks a lot for your contrinution! 🎉

**Comment by andrii-bodnar** [comment]
@duyguyildirantekin some checks have failed, please check [this](https://dev.azure.com/crowdin/crowdin-dotnet-client/_build/results?buildId=11669&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=b6761d2c-04f1-5cc8-8d6b-e444be405a7a)

**Comment by duyguyildirantekin** [comment]
> me checks have failed, please check [this](https://dev.azure.com/crowdin/crowdin-dotnet-client/_build/results?buildId=11669&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=b6761d2c-04f1-5cc8-8d6b-e444be405a7a)

hi @andrii-bodnar ,
I am not familiar with the error, however, I investigate the error, I found this article, could you check [this]( https://ryanhayes.net/azure-devproblem-starting-the-plugin-credentialprovider-microsoft-solved/)

**Comment by andrii-bodnar** [comment]
@innomaxx could you please assist with this?

**Comment by innomaxx** [comment]
> @innomaxx could you please assist with this?

Sure, thanks for the reminder.

**Comment by duyguyildirantekin** [comment]
@andrii-bodnar @innomaxx    is there a time assumption for merging this pull request?

**Comment by innomaxx** [comment]
> @andrii-bodnar @innomaxx is there a time assumption for merging this pull request?

In progress, sorry for the delay

**Pull request merged**
