### PR TITLE
chore(test): Refactor Core directory in the Crowdin.Api.Tests

### LINKED ISSUE #272: Refactor `Core` directory in the `Crowdin.Api.Tests`
We need to move the files in the `Core` directory (under the `Crowdin.Api.Tests` namespace) to the new `TestUtils` directory. The current structure is confusing, as developers expect the `Core` directory to contain only its specific tests.

_Originally posted by @EvilKot in https://github.com/crowdin/crowdin-api-client-dotnet/issues/271#issuecomment-2414595325_

### PR DESCRIPTION
**Pull request by EvilKot**
Closes #272 

Reaming folder with test utilities to `Testing/` instead of `/Core` to not to conflict with folder structure defined in `/src`.

Should be good enough.
Alternatively all tests could be moved into nested directory to avoid further folder conflicts, or even all test utilities and resources could be moved to a new project.

### CODE REVIEW

**Comment by andrii-bodnar** [comment]
@EvilKot, thank you! Passing it over to @innomaxx for review as well.

**Comment by innomaxx** [comment]
@andrii-bodnar @EvilKot nice work, but I suggest a slightly different approach.

To refactor the namespaces, we can make the following changes:
1. Rename the project `Crowdin.Api.Tests` to `Crowdin.Api.UnitTesting` (it looks better IMO).
1. Move all tests to `Crowdin.Api.UnitTesting.Tests.{ApiSectionName}` folders
    Core serialization and other tests place in root of `Crowdin.Api.UnitTesting.Tests`
1. Move all resources to `Crowdin.Api.UnitTesting.Resources` folder.
1. Move helper and utility classes to `Crowdin.Api.UnitTesting` folder.

**Comment by EvilKot** [comment]
image

**Review by innomaxx — CHANGES_REQUESTED** [review]
Good job! Thank you
Please make the following changes to finish the work:

1. Rename `Crowdin.Api.Tests` in FS to `Crowdin.Api.UnitTesting`
2. Move the test in `Crowdin.Api.UnitTesting.Tests.Core` to the upper level (`Crowdin.Api.UnitTesting.Tests`).
3. Move all tests in `Crowdin.Api.UnitTesting.Tests.Common` to the same level as in the previous step.
4. Delete folders `Core` and `Common`
5. Ensure all types and resources on all namespaces match their folder structure

**Comment by EvilKot** [comment]
Hey, sorry for a long reply.

It seems i've messed up with merging latest changes, i also have 3 extra files appeared in this commit -
Readme.md and two files in Crowdin.Api.Translations 😬

I've created new PR #278 with all the changes applied from scratch in a single commit, if it's ok. 
Or i can attempt to fix current one.

> 1. Rename Crowdin.Api.Tests in FS to Crowdin.Api.UnitTesting
2. Move the test in Crowdin.Api.UnitTesting.Tests.Core to the upper level (Crowdin.Api.UnitTesting.Tests).
3. Move all tests in Crowdin.Api.UnitTesting.Tests.Common to the same level as in the previous step.
4. Delete folders Core and Common
5. Ensure all types and resources on all namespaces match their folder structure

1-4 Done
5 - files under `Crowdin.Api.UnitTesting`, `Crowdin.Api.UnitTesting.Resources`, `Crowdin.Api.UnitTesting.Tests` looks fine, `Crowdin.Api.UnitTesting.Tests.{ApiSectionName}` and below, like `Crowdin.Api.UnitTesting.Tests.Webhooks.Organization` partially checked, renaming was done for all by IDE.

**Comment by innomaxx** [comment]
Answered in #278

**Pull request closed without merging**
